test_get_nb_char (__main__.TestExercice) ... FAIL
test_get_nb_words (__main__.TestExercice) ... ERROR
test_pair (__main__.TestExercice) ... ok
test_remove_third_char (__main__.TestExercice) ... FAIL
test_replace_char (__main__.TestExercice) ... FAIL

======================================================================
ERROR: test_get_nb_words (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 75, in test_get_nb_words
    output = [exercice.get_nb_words(v[0], v[1]) for v in values]
  File "test_exercice.py", line 75, in <listcomp>
    output = [exercice.get_nb_words(v[0], v[1]) for v in values]
TypeError: get_nb_words() takes 1 positional argument but 2 were given

======================================================================
FAIL: test_get_nb_char (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 65, in test_get_nb_char
    "Mauvais calcul du nombre d'occurences du caractère"
AssertionError: Lists differ: [7, 12, 4] != [4, 1, 0]

First differing element 0:
7
4

- [7, 12, 4]
+ [4, 1, 0] : Mauvais calcul du nombre d'occurences du caractère

======================================================================
FAIL: test_remove_third_char (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 33, in test_remove_third_char
    'Retrait du mauvais caractère'
AssertionError: Lists differ: ['heyjad!', 'abcefg', '0124'] != ['he jad!', 'abdefg', '0134']

First differing element 0:
'heyjad!'
'he jad!'

- ['heyjad!', 'abcefg', '0124']
?     ^          ^         ^

+ ['he jad!', 'abdefg', '0134']
?     ^          ^         ^
 : Retrait du mauvais caractère

======================================================================
FAIL: test_replace_char (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 49, in test_replace_char
    'Erreur dans le remplacement de caractère'
AssertionError: Lists differ: ['hey yad!', 'baaaab', 'a1234'] != ['hey yad!', 'bbbbbb', 'a1234']

First differing element 1:
'baaaab'
'bbbbbb'

- ['hey yad!', 'baaaab', 'a1234']
?                ^^^^

+ ['hey yad!', 'bbbbbb', 'a1234']
?                ^^^^
 : Erreur dans le remplacement de caractère

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=3, errors=1)
